version: "3.3"
services:
  dart-container:
    image: dart:stable-sdk
    container_name: "dart-container"
    working_dir: /mnt
    volumes:
      - ./solution:/mnt
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]
